@startuml

class Model {

}

class DeepAgent {

}
DeepAgent "1" *-- "1" Model: estimator >

class DeepQAgent {

}
DeepQAgent --|> DeepAgent

class DoubleDeepQAgent {

}
DoubleDeepQAgent --|> DeepAgent

class A3CAgent {

}
A3CAgent --|> DeepAgent

class RandomAgent {

}
RandomAgent --|> DeepAgent

@enduml
