"""Modern Gymnasium environment tools for Mario RL experiments."""
from .actions import (
    ACTION_SETS,
    DEFAULT_MACRO_ACTION_SET,
    MACRO_ACTION_SET_DESCRIPTIONS,
    NATIVE_ACTION_COUNT,
    NATIVE_ACTION_SET,
    MacroAction,
    ResolvedActionSet,
    ResolvedMacroActionSet,
    action_set_summary,
    get_action_set,
    macro_action_summary,
    resolve_action_set,
    resolve_macro_action_set,
)
from .config import MarioEnvConfig
from .factory import make_env
from .tasks import (
    AdaptiveCurriculum,
    CurriculumTaskProgress,
    MarioTask,
    TaskFeatureEncoder,
    TaskFeatures,
    TaskSuite,
    TaskSuiteConfig,
    UNKNOWN_TASK_VALUE,
    available_env_ids,
    available_tasks,
    build_task_sampler,
    choose_stage_env_id,
    encode_task_features,
    smb3_stage_matrix,
    task_feature_size,
    task_for_env_id,
    task_for_env_id_or_none,
)
from .wrappers import (
    ClipRewardEnv,
    DefaultSeedEnv,
    DownsampleObservationEnv,
    FrameStackEnv,
    MacroActionEnv,
    MaxFrameskipEnv,
    OpenCVLiveRenderEnv,
    OpenCVRecordVideoEnv,
    TrainingTimeoutEnv,
)


__all__ = [
    "ACTION_SETS",
    "AdaptiveCurriculum",
    "ClipRewardEnv",
    "CurriculumTaskProgress",
    "DEFAULT_MACRO_ACTION_SET",
    "DefaultSeedEnv",
    "DownsampleObservationEnv",
    "FrameStackEnv",
    "MACRO_ACTION_SET_DESCRIPTIONS",
    "MacroAction",
    "MacroActionEnv",
    "MarioEnvConfig",
    "MarioTask",
    "MaxFrameskipEnv",
    "NATIVE_ACTION_COUNT",
    "NATIVE_ACTION_SET",
    "OpenCVLiveRenderEnv",
    "OpenCVRecordVideoEnv",
    "ResolvedActionSet",
    "ResolvedMacroActionSet",
    "TaskFeatureEncoder",
    "TaskFeatures",
    "TaskSuite",
    "TaskSuiteConfig",
    "TrainingTimeoutEnv",
    "UNKNOWN_TASK_VALUE",
    "action_set_summary",
    "available_env_ids",
    "available_tasks",
    "build_task_sampler",
    "choose_stage_env_id",
    "encode_task_features",
    "get_action_set",
    "macro_action_summary",
    "make_env",
    "resolve_action_set",
    "resolve_macro_action_set",
    "smb3_stage_matrix",
    "task_feature_size",
    "task_for_env_id",
    "task_for_env_id_or_none",
]
